#!/bin/sh
# The next line is executed by /bin/sh, but not tcl \
exec wish "$0" ${1+"$@"}

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

# run.tcl --
#     Auxiliary script to run the examples
#

#set dir ../../modules/controlwidget
#source $dir/pkgIndex.tcl

#source [lindex $argv 0]

#------------------------------------------------------------------------------

lappend auto_path \
   [file join [file dirname [info script]] "lib"] ;# "../common"

source "examples/demo-meters.tcl"


#------------------------------------------------------------------------------
