#!/bin/sh
#
#-----------------------------------------------------------------------

CUR_DIR=$PWD

NAME=urqmd-afterburner-master

#cd $CUR_DIR/urqmd-afterburner-master

#-----------------------------------------------------------------------
#
# Compile and install:

#     mkdir build && cd build
#     cmake .. [-DCMAKE_INSTALL_PREFIX=<prefix>]
#     make install

mkdir -p R/obj

cd R/obj

#-----------------------------------------------------------------------

cmake -DCMAKE_INSTALL_PREFIX=$CUR_DIR/R ../../$NAME  | tee  $CUR_DIR/cmake

make install 2>&1 | tee   $CUR_DIR/make_install

#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
