# -*-   mode: makefile ; coding: koi8   -*- ------------------------------------
#
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

all:  
#	(cd OlliverForman/GraphRicciCurvature; make)

test:  
	(cd OlliverForman/GraphRicciCurvature; make test)
#	(cd OlliverForman/GraphRicciCurvature; T.sh)

#-------------------------------------------------

clean:  
#	(cd OlliverForman/GraphRicciCurvature; make clean)

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
