#!/bin/sh
#
#-----------------------------------------------------------------------

CUR_DIR=$PWD

cd $CUR_DIR/freeglut-3.2.2

#-----------------------------------------------------------------------
#
#
#-----------------------------------------------------------------------

#cmake -DCMAKE_INSTALL_PREFIX=$CUR_DIR/R   .   2>&1 | tee  $CUR_DIR/cmake

#make         2>&1 | tee  $CUR_DIR/make  

make install 2>&1 | tee   $CUR_DIR/make_install

#-----------------------------------------------------------------------
   
#./configure --prefix=$CUR_DIR/R  2>&1 | tee  $CUR_DIR/configure  

#make         2>&1 | tee  $CUR_DIR/make  

#make check   2>&1 | tee  $CUR_DIR/make_check 

#make install 2>&1 | tee   $CUR_DIR/make_install

#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
