#!/bin/sh
# The next line is executed by /bin/sh, but not tcl \
exec wish "$0" ${1+"$@"}

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------


# lappend auto_path \
#   [file join [file dirname [info script]] "plotchart"] ;# "../common"

# package require common 1.0

# package require Plotchart


#source "plotchart/plotchart.tcl" ;# загружает остальное !!

source "lib/plotchart.tcl" ;# загружает остальное !!

#-------------------------------------------------------------------------------

    canvas .c -background white -width 400 -height 200
    pack   .c -fill both

    #
    # Create the plot with its x- and y-axes
    #
    set s [::Plotchart::createXYPlot .c {0.0 100.0 10.0} {0.0 100.0 20.0}]

    foreach {x y} {0.0 32.0 10.0 50.0 25.0 60.0 78.0 11.0 } {
        $s plot series1 $x $y
    }

    $s title "Data series"

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

