# -*-   mode: makefile ; coding: koi8   -*- ------------------------------------
#
#-------------------------------------------------------------------------------

TENSOR_DIR = ../tensor		

#OTHERS_DIR = ../others

HPOKER_DIR = ../hpoker

##LISPER_DIR = ../lisper

#-------------------------------------------------------------------------------


all:  TENSOR__ # HPOKER__ # OTHERS__ LISPER__  

#-------------------------------------------------------------------------------

TENSOR__ :
	(cd $(TENSOR_DIR); make)

# OTHERS__ :
# 	(cd $(OTHERS_DIR); make)

HPOKER__ :
	(cd $(HPOKER_DIR); make)

# LISPER__ :
# 	(cd $(LISPER_DIR); make)

#-------------------------------------------------------------------------------

clean : 
	(cd $(TENSOR_DIR); make clean)
#	(cd $(HPOKER_DIR); make clean)
#	(cd $(OTHERS_DIR); make clean)
##	(cd $(LISPER_DIR); make clean)

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
