#!/bin/sh
#----------------------

# ------------------------------------------------------------------
# 

#LANG=C ecl --noinform --eval '(require :sb-posix)'   --script $*  

#LANG=C ecl --shell $*  

ecl --shell $*  

#
#----------------------
