# -*-   mode: makefile ; coding: koi8   -*- ------------------------------------
#
#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

all: 
#	(cd CIPS;              make)
#	(cd GOCR/gocr-0.52;    make)

	(cd TOOL/xdotool;      make)
	(cd TOOL/xzoom;        make)
#	(cd TOOL/yzone-m;      make)

# test:  
# 	(cd ext/m; M)
# 	(cd src/m; M)

#-------------------------------------------------------------------------------

clean:  
	(cd CIPS;              make clean)
	(cd GOCR/gocr-0.52;    make clean)
	(rm -f GOCR/gocr-0.52/src/gocr)

	(cd TOOL/xdotool;      make clean)
	(cd TOOL/xzoom;        make clean)
#	(cd TOOL/yzone-m;      make clean)

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
