# -*-   mode: makefile ; coding: koi8   -*- ------------------------------------
#
#-------------------------------------------------------------------------------


all: LIBS_make   

LIBS_make:
	(cd ../ploter; make)
	(cd A-ZONE;    make)
#	(cd A-FLTK;    make)
#	(cd AIGO12;    make)
	(cd SCRUZH;    make)
#	(cd Y-ZONE;    make)
#	(cd Y-FLTK;    make)
	(cd SOLVER;    make)

#-------------------------------------------------------------------------------

clean : 
	(cd ../ploter; make clean)
	(cd A-ZONE;    make)
#	(cd A-FLTK;    make clean)
#	(cd AIGO12;    make clean)
	(cd SCRUZH;    make clean)
#	(cd Y-ZONE;    make clean)
#	(cd Y-FLTK;    make clean)
	(cd SOLVER;    make clean)

#-------------------------------------------------------------------------------
# 
#-------------------------------------------------------------------------------
